apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-soulsync.sops.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
metadata:
  name: soulsync
  labels:
    app.kubernetes.io/name: soulsync

