---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-system
  labels:
    app.kubernetes.io/name: kube-system
namespace: kube-system
resources:
  - coredns-config.yaml
