apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - secret-profilarr.sops.yaml
  - httproute.yaml
metadata:
  name: profilarr
  labels:
    app.kubernetes.io/name: profilarr
