apiVersion: v1
kind: Secret
metadata:
  name: profilarr-secrets
  namespace: profilarr
  labels:
    app.kubernetes.io/name: profilarr-secrets
type: Opaque
stringData:
  # TODO: encrypt with sops
  api_key: ""
sops:
  version: "3.11.0"
