apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-secrets
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin-secrets
type: Opaque
stringData:
  # TODO: replace with real credentials and encrypt with sops
  admin_username: ""
  admin_password: ""
sops:
  version: "3.11.0"
