apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tado-proxy-data
  namespace: tado-proxy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-spacex
