apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tado-proxy-data
  namespace: tado-proxy
  labels:
    app.kubernetes.io/name: tado-api-proxy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-spacex
