apiVersion: v1
kind: Secret
metadata:
    name: tado-proxy-secrets
    namespace: tado-proxy
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:0J2xjJMs1j+vk0ZMLmEMjCdiniQze4DEtw==,iv:0KI2T2mOSf8TVDauqI21ZtDA75KHGCgCHipyDkE5OGU=,tag:AhB/wMnvC0lNBwrCIHUIbQ==,type:str]
    password: ENC[AES256_GCM,data:feNAVleLjZKq+EhjbK1KgW0QB9Eo,iv:Q0Hprx2uRsog1tnTpCR6R7Ni69ifrFVgUsUiFxTe5mo=,tag:iAOB5CT2zJCAF1w4byIy/Q==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeC9ibHlDdnBEMVowWEwv
            TzNqajMxYS9EaVh0enJIVWJZaW03OGovZUhvCkNpR2FnZWFob1BOYkFob0JCMFZs
            Z2E4RlYramxhVUw4OFZTUHUxOGI2aG8KLS0tIGJpMHJHWlJwenZtQ2JCNDd2a3Bl
            OGxBYTkzWmpVOEJmTzd2TW8vQk4rMDQK6H5o/peRZTEKJJX5SJfTUSvayu5SBJlf
            NIuoLrgfKyHXD0BijA8XOhRvzmXe88YmpnQgcjBzDP0n73dERvS8ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T16:16:26Z"
    mac: ENC[AES256_GCM,data:h910CDBcLmRYD38tLPEQzfS3YS8Rs8pHJe+LTBmgYZHhDkmm6bhZhANbqwUAIosqNcIObZMTVl8lHGQrKnBUbiMLfZzjCHE++IkY4ztLFbe/CbdCghoysn8a/mftPkBoRKzkm1MY5c1PDkqHJBhdudyxRjhylHm3GD7FF0CWTxY=,iv:p2jtxmsKSkq7QINnXOWwOFgKe0fMkpzZw9azHJLRqBA=,tag:VjJPiDThhSE/Ov9y9JWTQw==,type:str]
    encrypted_regex: ^(passwd|user|password|stringData|secret\.yaml|auth_token|network_key|mqtt_.*)$
    version: 3.11.0
