apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - secret-transmission.sops.yaml
  - secret-lidarr.sops.yaml
  - secret-prowlarr.sops.yaml
  - secret-musicseerr.sops.yaml
  - secret-soulsync.sops.yaml
  - secret-slskd.sops.yaml
metadata:
  name: media
  labels:
    app.kubernetes.io/name: media
