apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-shared
  namespace: media
  labels:
    app.kubernetes.io/name: media-shared
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-spacex
# Shared media/downloads PVC (RWX)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: media
  labels:
    app.kubernetes.io/name: transmission-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-flash
# Small config PVC for Transmission (in media namespace)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: media
  labels:
    app.kubernetes.io/name: lidarr-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-flash
# Small config PVC for Lidarr (in media namespace)

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
  labels:
    app.kubernetes.io/name: prowlarr-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-flash
# Small config PVC for Prowlarr (in media namespace)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicseerr-config
  namespace: media
  labels:
    app.kubernetes.io/name: musicseerr-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-flash
# Small config PVC for Musicseerr (in media namespace)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulsync-config
  namespace: media
  labels:
    app.kubernetes.io/name: soulsync-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-flash
# Small config PVC for SoulSync (in media namespace)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aurral-config
  namespace: media
  labels:
    app.kubernetes.io/name: aurral-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-flash
# Small config PVC for Aurral (in media namespace)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
  namespace: media
  labels:
    app.kubernetes.io/name: slskd-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-flash
# Small config PVC for SLSKD (in media namespace)
