apiVersion: v1
kind: Secret
metadata:
  name: transmission-secrets
  namespace: media
  labels:
    app.kubernetes.io/name: transmission-secrets
type: Opaque
stringData:
  webui_username: "admin"
  webui_password: "AF(pb4'au8A)2{U^ok%1,|'k)("
sops:
  version: "3.11.0"
