apiVersion: v1
kind: Secret
metadata:
    name: transmission-secrets
    namespace: media
    labels:
        app.kubernetes.io/name: transmission-secrets
type: Opaque
stringData:
    webui_username: ENC[AES256_GCM,data:1Pt5uHs=,iv:KQ/sXtd4T3tl2skJCFpmQ+Wepz+I4Aaq2/14ex9Fpk4=,tag:4hMoSAQPTeDJTLklKodZXA==,type:str]
    webui_password: ENC[AES256_GCM,data:zT+Mnwx8brHeS24/YHOQ5eqUroe/1kKEIhY=,iv:xd9CoqQdSoqwFF8DK/+yOZc68dm1pCmmCg+DNbOVp0k=,tag:UbLMz5aaWwd4qW2t4v0HAQ==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRlBubjl6akNyYzBobWxz
            cmJyM1JZVGQ0cEFSU1pFaEtvbkNMcHFiQ3d3CktkMDYyK0I1OTlYZlluQjJrSWho
            ZktoTG5oaDdUSDFxK1dwK3BVTzhtZzQKLS0tIEZuRVYzKzFTVW5lMTRqVGRqVTJD
            blhnR0xKNVVseWpON2ExRTR0dnRyblUKx52ZFRV749q97SxhXhAYHkMZoItsvozY
            NXZBogPFstDnae6mrbrvDflAwFUWzyZP+DwR0I3jPd2wnOMe9KG+IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T09:23:30Z"
    mac: ENC[AES256_GCM,data:OjbjYuQEFIfF/iRoww+4W6yS3gs4bnmVZAXvy6jZZt+sJtYtOSIlDeiOkty77c/5yyOU4W8vEGHC2Za9o8Za+qMGvHhocizLkGQ8hdjOKN7S6WOpDJ8V86QYmmNRLvFkt/ND7mBMp3ulyA5GlFO5OeHepg8qfpA0gQbonAxg+2w=,iv:SppjhC69e689uWs2CK8c3pKz0pu1fcudHaMcDJCTJbo=,tag:JrJjy6IW4fb5ys9fJRmORw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
