apiVersion: v1
kind: Secret
metadata:
  name: transmission-secrets
  namespace: media
  labels:
    app.kubernetes.io/name: transmission-secrets
type: Opaque
stringData:
  webui_username: "admin"
  webui_password: "4H(pq4'hu8V)2{U^ok%D,|'k)("
sops:
  version: "3.11.0"
