apiVersion: v1
kind: Secret
metadata:
  name: flaresolverr-secrets
  namespace: flaresolverr
  labels:
    app.kubernetes.io/name: flaresolverr-secrets
type: Opaque
stringData:
  # TODO: encrypt with sops
  api_key: ""
sops:
  version: "3.11.0"
