apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: twin
  namespace: flux-system
  labels:
    app.kubernetes.io/name: gatus
spec:
  interval: 1h
  url: https://twin.github.io/helm-charts
