apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: gatus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-spacex"
  resources:
    requests:
      storage: 200Mi
