apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: gatus
  labels:
    app.kubernetes.io/name: gatus
  annotations: {}
  # Required metadata for validation
  # app.kubernetes.io/name label added
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-spacex"
  resources:
    requests:
      storage: 200Mi
