apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
    namespace: gatus
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:+kw1+ZqGv6lQvTsjutLhYYE1oDI5tGMyo7mIik5JshU5UyGupYhe4Q==,iv:KY2ayXP+G1EKnP0+Yok9b2Cs3dtrOV0DofA6Nj5AVNU=,tag:A4MXjFoNgR1u+dRNii/zUw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:gqrip3pdoMSTVwfIfoy3UVcxw1TtabSN82ifc3vrhjyXqlEy0Pnh9KDrpGCzSogcf0VFGDFAbmxC4q0QKrRQt13tNqGPj1MISpnN+Qk7Q6dY0KDkEWCZOJs2h4jnc+iD6ijuANeULdw7MqU2SssGBeVCF1md1kyt3mKZKs0eLx8=,iv:JbYKNb/31Hgvg/OLASfGS0p9ONiml9aqHjkdyaTrFtA=,tag:ZHEd0hAA9xRJCXFYJD/idg==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:ILDNmvXKY1Y=,iv:Tk86sWdfvc4+t3BfJZhUT8adNDRYQ8KXObKY47Xg27o=,tag:kw9bwzLexIAUjVlJTX6Egg==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:tlFKLhwlFStPuxDwpY/uEfNoLj6Ruu15lE+vkXtBr2BtUOh8r/NnmE6AR1AypQ==,iv:JAI4jVxfKR9JpQmZSMfW0ja+jcL+9utLh3i6z5+p45k=,tag:WjKYs3OE9GE/StYjzjsRww==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQWtQLzNNaU1tU2hhbit6
            ejNkeS9RcjVlZzFpQ0N5WitMOEhTaDg4YURBCkpCNGRVelRsMlZuTG12T3RHR0F0
            dUlvTWFreVM3ZWFNZHNkTTYveFp3UHMKLS0tIDIxNG50UlFXUG9sWFh2Wnk5RDBk
            YlBGREFnT1J0bGI0ZnVxQXNKemsxOVEKjyDCboVP3PHwoDkVijNvhdhXTLcZ8Qgf
            SDdCAIgeP78LN39CH+tJt/RQaTyQ+sOxjBJFhPHoZ7n6hcFzKUvS0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T07:58:17Z"
    mac: ENC[AES256_GCM,data:YGVdB3upr1Oc4Duy0ilY+MtNaSGgCNoLA+LKhlDjbMXeYsQsFkpcVOi7WCpeUDzguKCk4+09/ti1r/RDaVyAF7FEZ2K46VVl9nb92HT2yp3uyMjvoDA5b1OscpsjvP95BmT59Yp7XTiBWJi1/vjkrd7707QyLFqFso304+jrbV0=,iv:54Frh9ioKgALeorq5ANnFk0Fs2wLGPiXIK8yLwxExJ4=,tag:vBn/Sd1LWmJdPdvIaWLzNQ==,type:str]
    encrypted_regex: ^(passwd|user|password|stringData|secret\.yaml|auth_token|network_key|mqtt_.*)$
    version: 3.11.0
