apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-spacex


---

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-certs
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-spacex
    

---

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-templates
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-spacex