apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-secrets
type: Opaque
data:
  secret-key: ENC[AES256_GCM,data:2UHYU2vuh/e0eoIbxD60GB/OzGrCgi3Een5nBGf+DWgz7ecvS0DL304CZ9yiwG/svSahLDjvuu7lpp/huVpSW3b6c2nH168Fd9XGeYVdPBdQGcZmHXOWiDww+9aGgr6I8Szi7fc6XWFPUO8j,iv:2hZCWowLZOYju2agkoopNzA3Q6yDmBsLkSwu0/91E9Q=,tag:Rigiyfkv49vQoDl6uAzFyQ==,type:str]
  email-password: ENC[AES256_GCM,data:tSwku1NCWxsE9++n+vZ7U4Kbt3w=,iv:qXoJUPmmBilU6d7BMg2nh42F/N0+YrSiB0/8JUrT8c4=,tag:ejlfGw3Y2VQIf0AIBbxDhQ==,type:str]
  ldap-token: ENC[AES256_GCM,data:WtC4d0nrb9CqX0Nf/Jdz7MkLcUtmiC3QG0vpeKg34GsHUIEzA9qn1wgr5cEmCaEMWaFvnaNmKrZOEx4F4ZVO6VeILuajMoLx8qaohx63qZXZ10rpTqxe7r1SVUq6C6BQCxDwuaEFRkIDuEeQEGauFkjqwIePSXmOmPFo0yEryBxMQ6Jx4Hw9ruTikjb72ejvYrC9bCu9S9zyqbxw8LIIED8Q+kQDVzCf0dS1sA==,iv:3UEHicbMdhcQ25++FTkovwLwwVgoMEtGkPO66OxCklI=,tag:zF+Bebd/PCk/YPL8l86SRA==,type:str]
  email-from: ENC[AES256_GCM,data:aZihW98At6YgGOBPk15/8P6yHP3KYtMIJoAUY/A3fEc=,iv:G2F1R9ybznMiiu86p42h7tEQKcLyzkcvORCsSpVZMmc=,tag:OEgf8QcWMY6X9gPl+ndWsw==,type:str]
  email-host: ENC[AES256_GCM,data:U/m7XZP/iv6c0RJP2G/i5w==,iv:Xx/kzxsz1v0l+zXAx+KrEWwfHOtp4m4SrGddh6o2ApQ=,tag:ylPlW2l6BtYzQ+sMfq2yAA==,type:str]
  email-username: ENC[AES256_GCM,data:xsCR8B1XMYOX7atLDuJms6xZK/iIX3Ao08DHYru5Yss=,iv:qgSybrUqGig38zr4+2EX9hjQDN00SRzGPDzm9CYkfJo=,tag:BdfHbYw54v3aNZX5Eh7z/g==,type:str]
  postgres-username: ENC[AES256_GCM,data:HberqnGpub/1pTCE,iv:MJ5j6+1iYShh5WROL4O4Fd/CQHRYZaTvlFbXdM7XuAw=,tag:Senh6p1VaoOsaP4RvPuiPw==,type:str]
  postgres-password: ENC[AES256_GCM,data:/QdWos1yxpURrlSoBibLwnfSx0rKJ5mPTpTVwmpKcV8/xzWgu3SKP4KQAruwAVW8oMaoTBDlGgClQHnVIwjmmg==,iv:+AGFqPuDvFGyMHydVWjdEAfrX+1A0rfzcdMSXut/jwo=,tag:pY4y5aZAJYePaepJK+FOww==,type:str]
sops:
  age:
  - age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
  lastmodified: '2025-11-26T16:06:58Z'
  mac: ENC[AES256_GCM,data:VEF9Q33QpmAgiZ7V3TqYalAJpSPjR6JkUFgsWWEOuCB52+XGzOlY8RL1HNQmoWRI/XliaDJCrVQQ9ruCABTKJUSTmNMq/oPtG6BQ8NXPPj3DbUTp/a2w8ADrivHb11sWevIz4M12CN07kGZBeA8istn6vqYl2rAx7Ft/WlU7XBQ=,iv:uyOQyKL86R2bBRU1zb2CDrTmlSoNio7CaE+L5DytNas=,tag:QsUHBZEAPi5vTMbO8j6mow==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
