apiVersion: v1
kind: Secret
metadata:
  name: telegram-credentials
  namespace: flux-system
  labels:
    app.kubernetes.io/name: telegram-credentials
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:ocs0ULlQ+szMuUEqGS2czRSvhsADkyKQZ4uGOjtjPCzV+bQkJOSBo9xp9x/DCw==,iv:V4pgtzqoiO4tmOPFTNqjbIeP207U2uQ5pDRVaw/SjlU=,tag:KMEkWQfpCh/uMAKOsSQrpg==,type:str]
sops:
  age:
  - age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
  lastmodified: '2026-05-06T14:19:15Z'
  mac: ENC[AES256_GCM,data:eDAuVmjdjFPWtK273mMqzgUOr2MTVMyGteMR8wthH7NRmF0BExO601xnp+YG+0kBxKyIO07WOETiIXZaQsWiE/wjMxWZcN8+1LR2N3jyzTxhKjDKlHnxo9iEfI1mHCsPEsoGQoQg03NA9RlkuaRGNXh6oONxekJo/R8Ot5gFzGY=,iv:GM/h+qtiqF3LABT4y3Cs8YhmJgeFgVSXokZmHeOmIys=,tag:wqTGQkXOABE3uIC5DMc4eQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
