apiVersion: v1
kind: Secret
metadata:
  name: cluster-vars
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cluster-vars
type: Opaque
stringData:
  DOMAIN: ENC[AES256_GCM,data:aw6osIS/S/fA5rE2nCHzIRw=,iv:6TjQy549jS3ynp1NmQzQ09OzrHij2+GkQrFhdejgVPM=,tag:t94uzyqZ3NLuEUkb+7HJ7g==,type:str]
sops:
  age:
  - age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
  lastmodified: '2026-05-06T13:19:09Z'
  mac: ENC[AES256_GCM,data:FuK6cTX0E1OvlBmdDeoowabjJIaB3KgjILc9OVVWKVm4eJb6Fy1/RF3om7i8sj0aItAQY3AWGsK+cz4mPWDH9a/KZLG8ehvq4Xdc8TCi2tOr1slTXSkoT0btDgnvWarlvt6oRpbFaYXuHsc4hPJ1+BIJuH2OYRZSn2tvU+E5L2I=,iv:2CV23YKWSmveYW6YDHKvlgrx/DyoWWqM+eVYIhkqKT0=,tag:RG5AvIrb4uVsfpMik5ajWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
