# Procedura (una tantum):
#   1. Recupera i valori:  sops -d apps/gatus/secret-gatus.sops.yaml | grep TELEGRAM
#   2. Sostituisci i REPLACE_* qui sotto
#   3. Rinomina:  mv secret-telegram.sops.yaml.template secret-telegram.sops.yaml
#   4. Cifra:     sops -e -i infrastructure/secrets/secret-telegram.sops.yaml
#
# Questo è l'UNICO file che contiene le credenziali Telegram.
# che vengono sostituiti da Flux via postBuild.substituteFrom.
apiVersion: v1
kind: Secret
metadata:
    name: telegram-credentials
    namespace: flux-system
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:ocs0ULlQ+szMuUEqGS2czRSvhsADkyKQZ4uGOjtjPCzV+bQkJOSBo9xp9x/DCw==,iv:V4pgtzqoiO4tmOPFTNqjbIeP207U2uQ5pDRVaw/SjlU=,tag:KMEkWQfpCh/uMAKOsSQrpg==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZkFWTkt2U0FOZFZJam02
            UHJJTC9UZEwxbjlFR0xoWEI5aGswOWdJV1JNCk12dWRKUUUwZTE2VitMZ1hDNkpm
            cWsvaURReU5XL3hseWVVZG5jbEhUYjQKLS0tIFlzMmRPYkhoM0gvUkc0dUhQK3lZ
            Qm9YSmk4enMyZ0F4dkowL015TVBBYTQKQhqi6w+3Go1w/V9W1OfOvYPHhzYETOIK
            xsLhPSMsla2lwX42vFwqP8Tby5ISGbvYM3yng8ti8nNbY/LLopYyfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T14:19:15Z"
    mac: ENC[AES256_GCM,data:eDAuVmjdjFPWtK273mMqzgUOr2MTVMyGteMR8wthH7NRmF0BExO601xnp+YG+0kBxKyIO07WOETiIXZaQsWiE/wjMxWZcN8+1LR2N3jyzTxhKjDKlHnxo9iEfI1mHCsPEsoGQoQg03NA9RlkuaRGNXh6oONxekJo/R8Ot5gFzGY=,iv:GM/h+qtiqF3LABT4y3Cs8YhmJgeFgVSXokZmHeOmIys=,tag:wqTGQkXOABE3uIC5DMc4eQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
