apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-telegram.yaml
  - provider-telegram.sops.yaml
  - alert-flux.yaml
metadata:
  name: notifications
  labels:
    app.kubernetes.io/name: notifications
  annotations: {}
