apiVersion: v1
kind: Secret
metadata:
  name: musicseerr-secrets
  namespace: musicseerr
  labels:
    app.kubernetes.io/name: musicseerr-secrets
type: Opaque
stringData:
  # TODO: replace with real secrets and encrypt with sops
  admin_password: ""
  api_key: ""
sops:
  version: "3.11.0"
