apiVersion: v1
kind: Service
metadata:
  name: musicseerr
  namespace: musicseerr
  labels:
    app.kubernetes.io/name: musicseerr
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: musicseerr
