apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-storage
  namespace: lidarr
  labels:
    app.kubernetes.io/name: lidarr-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-flash
# NOTE: Use `nfs-flash` for small DB-like storage. If this PVC will store large media/downloads,
# change `storageClassName` to `nfs-spacex` and increase `storage` accordingly.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-media
  namespace: lidarr
  labels:
    app.kubernetes.io/name: lidarr-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-spacex
# Use `nfs-spacex` for larger media/downloads.
