apiVersion: v1
kind: Secret
metadata:
  name: lidarr-secrets
  namespace: lidarr
  labels:
    app.kubernetes.io/name: lidarr-secrets
type: Opaque
stringData:
  # TODO: replace with real secrets and encrypt with sops
  api_key: ""
  admin_password: ""
sops:
  # Populate sops metadata after encryption
  version: "3.11.0"
