apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: social-media-reuploader
  namespace: social-media-reuploader
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: ./charts/social-media-reuploader
      sourceRef:
        kind: GitRepository
        name: social-media-reuploader
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    serviceAccount:
      create: true
      name: ""
    image:
      repository: ghcr.io/lucaam/social-media-reuploader
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: false
    secret:
      create: false
      name: social-media-reuploader-secret
      botTokenKey: BOT_TOKEN
    env:
    - name: BOT_TOKEN
      valueFrom:
        secretKeyRef:
          name: social-media-reuploader-secret
          key: BOT_TOKEN
    - name: TMP_DIR
      value: "/tmp/telegram_downloader"
    - name: TELEGRAM_MAX_FILE_SIZE
      value: "52428800"
    - name: WORKERS
      value: "2"
    gui:
      enabled: true
      useSecret: true
      secretName: social-media-reuploader-gui-secret
      env: {}
      image:
        repository: ghcr.io/lucaam/social-media-reuploader
        tag: latest
        pullPolicy: IfNotPresent
      port: 8081
    db:
      pvc:
        enabled: false
