apiVersion: v1
kind: Secret
metadata:
    name: social-media-reuploader-secret
    namespace: social-media-reuploader
type: Opaque
stringData:
    #ENC[AES256_GCM,data:nYIna4Eo8cx3AUvlRiVfi343zqB7CowmNhAFc83ooWOIIrV+gc1gnwj14mAD9FiZ7HjG6LlI2keV1T/nsZLO18RafA/Z8LL6aWXDyfKwZSH2Xg==,iv:ddjTkiUrc/zxwyYtj70J9jViGklIyZXcNy+jVmmq28w=,tag:b25012BPGi7EvErPXzlUqg==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:56DoVYNWKTU0S+/5CxoLWtIkJDYxCO24QtxK0RFkTvWa3KKr88Ja+4eLQ/If4A==,iv:fiJCMio9USRahN1o9TRWqz++WgPak8UhOIy03XZvGms=,tag:7Nx+yjkHeWJcezYs5U9MYA==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTjlVYjZueFZ3d01iQmY4
            anNTbCthQnQzdlBCMGJaY0U3RlZxVjlyeWkwCjJYS0N2Ykd1Y0JBWG9DSDg4VGJk
            TzRUMjB0dFAvN0NDQ2FHTzNDa01uTWMKLS0tIFkwUUN1TDY5dmpOV0I0blp6NVZX
            L21zdHROdlU0ZkF6MVh5UGFqSjBETncKhiDFdEUz2C8zocJV+Ub7JpHuHy0jrztL
            zqOpQFbFYa6wBmzJk5zaseTLUgxXuaBdOYehV7zffRwwdFFGJSW/7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T11:42:10Z"
    mac: ENC[AES256_GCM,data:BbbeowjsHyifcfZD3G3BAlMVhLQLLJklmyCauiCi2LHcJzl0kU8ZPqlKyiXZozp+A2PdnMQ6dv0MvW4sgg4Gm19cVr9incUm/F/hYFSYVnMS0ybEDvbQfxv7oW2/3ByVV0D8ma3oQzb8pQew6E0sihE9Q8OvV/CMpQhA8Gv3Pmw=,iv:EQaNY5mH/qEtBcKpd7To5kCY/t3ORp8GcwtBJ0LQLzY=,tag:8JKijtgeqSIN9rb4RKFnQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: social-media-reuploader-gui-secret
    namespace: social-media-reuploader
type: Opaque
stringData:
    #ENC[AES256_GCM,data:QQSlnfmXIfFx/JIBEdF87K/AwKaefaKdkZu8wI0IzYRW417tAqsVeRBgJPaLGniwS5OZFboinVg9LpfU4Uaq1nWRi6ZgLO1guc4iBI0=,iv:VBPzuHr/yNDmIKXl0bgcPtMi/od7eNYwCM82u22Iz9c=,tag:hjPJRpll7K/0fALwT0NMvw==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:56DoVYNWKTU0S+/5CxoLWtIkJDYxCO24QtxK0RFkTvWa3KKr88Ja+4eLQ/If4A==,iv:fiJCMio9USRahN1o9TRWqz++WgPak8UhOIy03XZvGms=,tag:7Nx+yjkHeWJcezYs5U9MYA==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:1SAF82DCNa/aGYEslPqbmw==,iv:PdlQkniGEFKJjDGU6wDQIFIQG7UqJpgdOJSvvr2E7Lg=,tag:+rpyL9jfZ5koDtA73MQLTg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:N/ldpF/lfjrLuKdwgOt1aIeUo+UUTiDCCYtkRoalmetqZCKKGfPtV1hUyYoGhcOd7Qik7ivzFudyfirTwQrppQ==,iv:IerrlwDrrA9jGcSXbDbo29lLqXSJsfvn717XPNV/o3I=,tag:/6FBZVjogU1/Aiy6zOba2Q==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:gMq6Dq83SQmWX6EJqnbmo/hSjLBU0Yp3v/pTrt65k5IVjI9QrUoZNg==,iv:S+TpOiITReq1/yeNLy7GztYccw/J4w4lqFID2gkPAiQ=,tag:aU6HerZgH/UAwZJ0Q3xr1g==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lTCfVlRnnODxFDi7WrigLlpQ2WP+RqhWr3AP4YvoR+lVzlFweCzLhyujkfmyEpeJNqQGfnudgfLIvYnTfqALjC/yaKcLeNpASv6AD8/TvA3F/WES+mjA7p+/llssS9NfloHqeMC9em2kMyPcNa301BjUy9HBfyKSB6ms3X6t/zQ=,iv:6tmFHPnnNQYHZlg3TOQXtw+kyr8URaJsD6Av1TGo+mY=,tag:+vmWMwl/AqRbo9cFmI6bNA==,type:str]
    OAUTH_AUTHORIZE_URL: ENC[AES256_GCM,data:6u40IwmANMMJWQYnIgkxWJyceZ9qe0JCU1TM1qXjpQ0awMQkpBLisTb6827bN1O27LtjIhPQ5g==,iv:lODOq1PI1YIw17kJYuCrIVfyyknfYitijRcZGug7VdE=,tag:A2VwAhE/4V0DRg3KESKy5Q==,type:str]
    OAUTH_TOKEN_URL: ENC[AES256_GCM,data:j9+gA8lit+ljWwooiMTpyfHPEnfv4lvZH/qqfKVXYVPsy0MvOC7GCo8RcgWCWEpQaQ82,iv:H7IyGktgDBVYpbi7Ppm2/UmeJFuNZoOWEmkIE9dGpfw=,tag:deNRQln0OQ6zdz+R5Bw49Q==,type:str]
    OAUTH_USERINFO_URL: ENC[AES256_GCM,data:yvfWMYJJ0EeKNssxAVgERiL0jywwP3revYlLHoijj9WqiX0mYwrTzWUYOOIw/LzSVcJvftUp,iv:11Z3iOnjbcFKLPcLHZ8K4mzO9Yz5ISiY/iHcaILar2s=,tag:0xkm18CTVexii6ruWYZFZQ==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTjlVYjZueFZ3d01iQmY4
            anNTbCthQnQzdlBCMGJaY0U3RlZxVjlyeWkwCjJYS0N2Ykd1Y0JBWG9DSDg4VGJk
            TzRUMjB0dFAvN0NDQ2FHTzNDa01uTWMKLS0tIFkwUUN1TDY5dmpOV0I0blp6NVZX
            L21zdHROdlU0ZkF6MVh5UGFqSjBETncKhiDFdEUz2C8zocJV+Ub7JpHuHy0jrztL
            zqOpQFbFYa6wBmzJk5zaseTLUgxXuaBdOYehV7zffRwwdFFGJSW/7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T11:42:10Z"
    mac: ENC[AES256_GCM,data:BbbeowjsHyifcfZD3G3BAlMVhLQLLJklmyCauiCi2LHcJzl0kU8ZPqlKyiXZozp+A2PdnMQ6dv0MvW4sgg4Gm19cVr9incUm/F/hYFSYVnMS0ybEDvbQfxv7oW2/3ByVV0D8ma3oQzb8pQew6E0sihE9Q8OvV/CMpQhA8Gv3Pmw=,iv:EQaNY5mH/qEtBcKpd7To5kCY/t3ORp8GcwtBJ0LQLzY=,tag:8JKijtgeqSIN9rb4RKFnQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
