apiVersion: v1
kind: Secret
metadata:
    name: social-media-reuploader-secret
    namespace: social-media-reuploader
type: Opaque
stringData:
    #ENC[AES256_GCM,data:WoSBpqH0vG5tJLrAOzinXzIM9Q7zsM6d2Ab22fcx6TlYaCM9L/me/uNXi4Zy4JC6HrY+lJA5IVdhienhexC1nfHnLpcq6mpgklMA4DPYRHKNXQ==,iv:gj7ZkO6ue5IyJOvsyGYFFTDCYnuzvAG/N24hrtcGCwo=,tag:BfP4W3bMbzkZR4q3w5JBYg==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:+YC62Z9yhw3ZU6Wi+AkwX3kQm4BgJuOKMKjB9TpWkh8LDwudbmw1uYHySlGzng==,iv:Due2NkNFWzBQoKThgBRF+yZcXPU/2Yf8V0TRQEapHjA=,tag:wldH8S7fUqf7ymIj3qfk/g==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dkpJdmxadlJKRjI1ZGRv
            dGIwRzRTNHpTakMwQnRhYnhITGRKdm1YWEcwClBiUFVqQkdZaXZoRUVPMUFETzg2
            WmVTakJUNGpnT090QXBRQTByQk9lZTAKLS0tIElHcFJzcCtaOS83ck9PN0kvWCtZ
            K1RXeVdvb2xHWldwdHVrckZ3Y2dOdXcKyWMWO1iKsYwUZL/Yr9CWk8rnFZo2c32x
            ojZqnKMZJdYjL7fy3lcfXjD7ogWolE+XMwDAqgWxSGZXseHJZ7bjPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T16:46:21Z"
    mac: ENC[AES256_GCM,data:WtmcijwA9t6Da5mainudWuk8xYwlvKebApqo4SBwzS7Y6CiyRSFHGxd7K8Ha3HYJF891xtcQLz6K/j8fvkX04bQFIUTOzXURAweUh6Ql+XmH+Lo4CFfQ7z6MeEqfqOQ2PbWDyuLGG6MMwg7weH2ri+JB19Gr++x9Das6pBNF1PM=,iv:14CwwWG1ShlULA4EA1jKrejbpOesnGjuTiiQinnjRnQ=,tag:KxdR9Wlv9lV3gYIxZPjjVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: social-media-reuploader-gui-secret
    namespace: social-media-reuploader
type: Opaque
stringData:
    #ENC[AES256_GCM,data:c499bx50BLjiDVRNOEmZUufhT3jG+5jR23k6Yz0L7h25WyagjwfA+ugIxACj9BqYsjZlTocow/0oGVcB0sbVZHehQzVu/2zPCqI1NUQ=,iv:AgPpsGD1Md9zc2rPeG7mhi9AHBiIbc6A9o4y0nCcqHo=,tag:uKcK2o7JoNYn7lNILVr8tg==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:ZGVtb0FkbWluVG9rZW4=,iv:dHVlc2l2MTIzNDU2Nzg5MA==,tag:bG9uZ3RhZzEyMzQ1Njc4OQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:tThcM2wwf/NCXpOaBdjxc3t4dAZVaNCxAYikZC2QXDFc7gZ9X+KKTlgiyxP0mWB3SkQQtgbmPCvwutZjvD+NAw==,iv:mCUXaUDf+cLwBiltJ3SvJhVxwY/WJ22nPYYPe9lrWk4=,tag:iXIQekZfd/uz9T6/tFfx9A==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ZVYu7En4PdcCM58NTeQZ5GpqB+fYhMbR+ahsobSJauSyQ0h0S1jUJw==,iv:fibdQX5Lq5qSi4BEt9vPCGLFlu/JD0v8074d0pmsIm8=,tag:i9RZeWLasIPJKGoIj29dIA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:yijm98tXFl7Irh216cBY3u0hShUIwWjze6J8O1V2zFI0gJwD8zJvfoIoFtbE4N4nxl9vnHTmPYOUkLKJT/xBGCfFW9h7UtBlts8wD3yEBT6NZ+Wla2hR40DqYSezjJglTUnoptfypY3usamImMiMmxcepMRkeiA964IWzEiO1oA=,iv:3PATZJp545wgfVIwCEwhcfl9rDETsFS2S/mdyoWkoo0=,tag:Wg3+R1aSURQZENVwezTC5g==,type:str]
    OAUTH_AUTHORIZE_URL: ENC[AES256_GCM,data:afycUXrKop6+8iE65Y1+TeDRtRjzXg6nCSOsK+tm+oMdEkPyoz2inN9zAdH8L06u2OKsqPGZ6w==,iv:g4WJlbzSQDn/x8UcQlVU9PUpoTQhhU7dMMIFJcBeWyA=,tag:UZvsT1P3UnzZHNRkG1vAKw==,type:str]
    OAUTH_TOKEN_URL: ENC[AES256_GCM,data:76zgT/TDW0QJk4wNrUtovu+NC5uM0CTWyEdebEYWUoL6LjQVOF2AhBhNkr369nn1qdvk,iv:ehw5mndUq1ImknfAHX0c1y24A5URz+s0tS7Ht8Yreyw=,tag:GmQSati/Yuus0K0pu3A+IA==,type:str]
    OAUTH_USERINFO_URL: ENC[AES256_GCM,data:sOR8k0o9fwpbF0L1JX7kyassdjEvX6Bsmr6NwCxb9u78d8pMuB4brImfqcGBUTa4JvbCuuf+,iv:E6LTItP49A7g9bJhQ3YkUpdRRrxHG3svbUBCp3shM2Q=,tag:3ijxpVc3g4H45ddCD9hRJg==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dkpJdmxadlJKRjI1ZGRv
            dGIwRzRTNHpTakMwQnRhYnhITGRKdm1YWEcwClBiUFVqQkdZaXZoRUVPMUFETzg2
            WmVTakJUNGpnT090QXBRQTByQk9lZTAKLS0tIElHcFJzcCtaOS83ck9PN0kvWCtZ
            K1RXeVdvb2xHWldwdHVrckZ3Y2dOdXcKyWMWO1iKsYwUZL/Yr9CWk8rnFZo2c32x
            ojZqnKMZJdYjL7fy3lcfXjD7ogWolE+XMwDAqgWxSGZXseHJZ7bjPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T16:46:21Z"
    mac: ENC[AES256_GCM,data:WtmcijwA9t6Da5mainudWuk8xYwlvKebApqo4SBwzS7Y6CiyRSFHGxd7K8Ha3HYJF891xtcQLz6K/j8fvkX04bQFIUTOzXURAweUh6Ql+XmH+Lo4CFfQ7z6MeEqfqOQ2PbWDyuLGG6MMwg7weH2ri+JB19Gr++x9Das6pBNF1PM=,iv:14CwwWG1ShlULA4EA1jKrejbpOesnGjuTiiQinnjRnQ=,tag:KxdR9Wlv9lV3gYIxZPjjVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
