apiVersion: v1
kind: Secret
metadata:
    name: social-media-reuploader-secret
    namespace: social-media-reuploader
type: Opaque
stringData:
    #ENC[AES256_GCM,data:AQkGNrZhZSkhQZpjYa97jGAtpWaP9IjJjyGWCPD1F/TkXIeTi9XAyQsMj/Z2C0B/6HK9RNaUEQCHjGZd3dAEZLDNJpiO5PhUsW6vCEnIAO3J5A==,iv:Wd2jwIG7/8SncmkNgBiQYoSEGZT0YOnB9o50Q5wVO6U=,tag:yuICrRVcuaMeIluPsRkVKg==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:IIyeTSRWOr/qqVpWydNHrMl/b91LQXWw+JayaUeyQzNahXWnJyLqk+wpk7q3dQ==,iv:gFXel+UXllDUV5F7N7mgaWR1+bNplNDHj0bMeqobxIw=,tag:lMxX9k+MgebORbut+jMxAQ==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMnhUaFZaeUYwcDVwdmQy
            NzYyMjhxMnYrYklYb1lmRTZGdW8wT3ZHS2xzCmR4WjV5Y3JiOFEyTUtCQWJLR3Av
            NFQxeklVcEg5OTBTNktValdMZWpmdGMKLS0tIE5RREJ0RytiOTF6Q0dWd2lnUjJt
            TG9Nd01EVkMwakoxelFOeS9XeGdYaWsKPdr8zsOIkJfxWoTdVIPJqOWi/w86wK5K
            rz/eE+eRuO/a3Wfcn55bx9TslUTC7c/ZoRt9qO3TlSDHEs8ghu3ehw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T16:14:50Z"
    mac: ENC[AES256_GCM,data:KDKtGV8AounqkpsFvw2BaLjfdgJ114DoiL6f/5Au+uuDXBBq/CzBIqLba/bJqXypUoRJGJiALODI+Ewsm9Oy3u3QDuUPETr0xGCXYK5czHjTaJVerZGBlS/eYo+KpJSvDf4k0QbF9akjTP+8uMx7/eOOcFdfP6yGMCy/WUPxLJo=,iv:d8gpLms7WVhjZRXixZZH18sfIE+CN8WrlBoCYQJ+ss4=,tag:hCtYkOT5ZwlXLbI8OQrM0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: social-media-reuploader-gui-secret
    namespace: social-media-reuploader
type: Opaque
stringData:
    #ENC[AES256_GCM,data:R8SDjXbaia9V98HgT4n5DMkQJRdNb7MZjV/DEyWd/0lOlxZ9C6oa7WDxug41Bv4naGlmJ8iff80266THwdpWaQ4nTZM6U8ExNhBubDM=,iv:yrcwoxnMbMn89xdZz2iyGiMRH38+6u4EzMUjuTOP2OI=,tag:CVjpioJ+XY+yRqzJ5UHAFA==,type:comment]
    BOT_TOKEN: ENC[AES256_GCM,data:DwWdWGFic5FPVMOA8cM6R0KWS045QcIBB3oYaImmu0WdxsJcwZ6PsKV0GL3QyA==,iv:b6pJ665itDv+WJbWVVZfnn/2agaHm69AGEL41HBPimo=,tag:OCYcYcc3zu95dEjoIu7SuA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:D0c8we0RCiG5cQvQJFVvJC7bwNBa3mci6zXzVZK0JvNdeLUktYmTj/8cq+F+4qf2nI6wa2AuclG8aJnFz7VcTQ==,iv:KPJ3vySFvQBbGMVrcAAGCWH5sFsvrpxvQi/2hluswwk=,tag:0LDtaquXKJu/hwaVtSn+1Q==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:F5Gg9mme2kUTsgzbf2ydOM4EDAxSxx6CNeM+/NF+Very6TwOCutFog==,iv:9i/6fOj5/ACbC9IX58rg3QW1WABC8rrOu3ZZnurMW5w=,tag:8w9+6w45dlL9zl8zqD8V4Q==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:CEei3asYeqiSSvew5M75eBo2kCfMApL6MrHQgWHVqbKIq+HAQBPafQyZ1SOiI+C+LpPVSoDgS591PjzgDtP/WKCb6mjewD1FIwr1CkkPX/Bj6MeCZ/czjYq+x2OgscnsszZmGcJpwGUZn3SH1WhceMZboUn7+wfiVoXXw/DGFQk=,iv:VIq1JEANM5HaCUe31UxDDeLxyUD/cOHPBkuMlFQban4=,tag:Or+iOCfBpFRMKrszfjDQqg==,type:str]
    OAUTH_AUTHORIZE_URL: ENC[AES256_GCM,data:Q2EES1++M88l5SnnUx7ip/l3FEPM+CFPsLCkHIXbvC+hND+CxV8aFNEDyNNyRW1gGUZ50Pf5lg==,iv:IZzVywvIBhh2RUYcsg0a8txW7GzBr1FA5Gybhz+pcLw=,tag:DQ2f7GiR17+cYSfw3O3g8w==,type:str]
    OAUTH_TOKEN_URL: ENC[AES256_GCM,data:++tEGFV9nhyPDhEC1Z6U7Hv08QywF8OEuZ6wRvZgAbcawfxgM4kQf96jA0G+M0Mr2DqU,iv:SskVr8iD+boTDgvtEXCTC6IHv2hNe3QGP5Zn366vW3o=,tag:uR6eODz9OK3LuAr0BEzpew==,type:str]
    OAUTH_USERINFO_URL: ENC[AES256_GCM,data:5GlsViyEEha3y/63wNTL8ZHedCUVVE2R2/SZyC2dAkcV8xuc/OhYBmklFPvOkccv5B8t1+tN,iv:oqpv3GTQc7MntA+fLYXy6tf4r07RSoiZhqU+6GYu7n0=,tag:VWB6DEDFbJVha9OlzaA+1A==,type:str]
    OAUTH_JWKS_URI: ENC[AES256_GCM,data:mNQ9z4o78TlVij0semGagIwk5ebbVh+SbpjqPhHh9uA6WOfxhBph3mnbnACWiZPBem6axttoFk3GRUerggd/tqJaYT4vimX7qHbIYlx8,iv:kJ4MObBAg2iG3Zq05X4qq2QB+08pmfk0Qk2CNld7nfE=,tag:m76tKuh8JSlI5nZm5YiYrQ==,type:str]
    OAUTH_SERVER_METADATA_URL: ENC[AES256_GCM,data:MS3ouqs7Z4IY4OQnqLCVkN/hwtFwXk91mrJpF4GaoyXNmI7s8A7bTGPYJ/+K6oS1hxl0oiPcfZU03ENqWsCnkrF6bbh6YZrWBFiGSxBNIWDaXN/MX7UQVhmXwvb1dlgzcsHb4JYlxc22,iv:j48Q2yKQSBBBqQRff6Nmffi34jYX/gGkicshou3ug+c=,tag:BTgJDSrEdO3coA3IONqw0A==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMnhUaFZaeUYwcDVwdmQy
            NzYyMjhxMnYrYklYb1lmRTZGdW8wT3ZHS2xzCmR4WjV5Y3JiOFEyTUtCQWJLR3Av
            NFQxeklVcEg5OTBTNktValdMZWpmdGMKLS0tIE5RREJ0RytiOTF6Q0dWd2lnUjJt
            TG9Nd01EVkMwakoxelFOeS9XeGdYaWsKPdr8zsOIkJfxWoTdVIPJqOWi/w86wK5K
            rz/eE+eRuO/a3Wfcn55bx9TslUTC7c/ZoRt9qO3TlSDHEs8ghu3ehw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T16:14:50Z"
    mac: ENC[AES256_GCM,data:KDKtGV8AounqkpsFvw2BaLjfdgJ114DoiL6f/5Au+uuDXBBq/CzBIqLba/bJqXypUoRJGJiALODI+Ewsm9Oy3u3QDuUPETr0xGCXYK5czHjTaJVerZGBlS/eYo+KpJSvDf4k0QbF9akjTP+8uMx7/eOOcFdfP6yGMCy/WUPxLJo=,iv:d8gpLms7WVhjZRXixZZH18sfIE+CN8WrlBoCYQJ+ss4=,tag:hCtYkOT5ZwlXLbI8OQrM0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
