apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: trek
  namespace: flux-system
  labels:
    app.kubernetes.io/name: trek
spec:
  interval: 1h
  url: https://github.com/mauriceboe/TREK
  ref:
    branch: main
