apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-data
  namespace: trek
  labels:
    app.kubernetes.io/name: trek
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-flash
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-uploads
  namespace: trek
  labels:
    app.kubernetes.io/name: trek
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-flash
  resources:
    requests:
      storage: 20Gi
