apiVersion: v1
kind: Secret
metadata:
    name: trek-secret
    namespace: trek
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:e3MJBVY328r6SkoS30GyO6d+6pTFbzh5pIxQ6f3lWCaHetXzkjrVydQK1Ac=,iv:LTdeZdebZWRcnzl/qCvt88slYfnjzb/seTA7ZrJX0WE=,tag:gQita8/QONa/seceRA3IkQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:8U3YDpClO/ncb3xWKB/Awa1pe/8bagt9RbWiiDnEZsVSHHpgOHO2TQ==,iv:RSSulZ4+xnplXKmGubw/IqXg8dbLAOZdxG7PtgKTVEI=,tag:N0dZ4ZnVbUU6Rnq6xIbfXQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:DcjOXtEozmZqBBjy34hCEiP+xbSCxtbw8KWotkQRuRAbDoM23fUK3aWYZqmNXy/HM5cC/Cz9lBfX+C+UC+cPpcXrnKEM0HpNdGJSuXnCg8jc5szMctr7Y24t2lyRlYh5GujmCJGdNGmhzhMIYOWlhnPFptEyuWOlHYqgiOj/MxU=,iv:mfIiW8oR1R9GvveGFfpFD0W6zHPhk3rnitOXT4thUvU=,tag:9507J3eqX2h8U3mHUY/uTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVS91c1FDVkVlVmZUQVh2
            NEgrN3c1MDlXR0pDYlJHRm5QVGpLZy96NWhVCkFlaDV4ejJLQWlTMWs0ekpYSEdC
            bno2anpsb0MxM2lPMjVEbHNqaWxsYkEKLS0tIGdNbEJSbld0SGxpdmFJY2dnK1dx
            eG1lTzNrWEx4THRhc2sxbXhCelpaTGcKlwy12Qrw9Y90OT8XYMyXG/Ab6WzhslBA
            WdoPMHZ8pcNTlE2eKQv8PEiqZhmvBJh6/sb/P4KiuKYQxMOcvIcMXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T14:10:07Z"
    mac: ENC[AES256_GCM,data:GzylcZ81UC0054YA2i/AHGrQUhiaMbcXjaki7MpGiCMHnHKfmWPbduet5UcDOlpy6XjXXKS8ibIIKx/rOZ69q42s5NuTmTs42d1DizJIzQeZnTvPO8TQAh1wSSHqtZbaMS5tG1P0OQ3TMXLAijbtyhuYzc5PsNJQt0t2RN3MJY0=,iv:BLlZ9y+EDIzDHpQfYP+QhJmSmb3v0AeJmsHmEoxOBJA=,tag:7ymPjMrlqq3wQj6ID4H54g==,type:str]
    version: 3.13.2
