apiVersion: v1
kind: Secret
metadata:
  name: trek-secret
  namespace: trek
  labels:
    app.kubernetes.io/name: trek-secret
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:FO7HSF34MtIY5HXzQZwrXlMQ8qiKez5YQl6jZqO69YKeWkKPWZkdnOhloEo=,iv:rT4eVUh0AoosUhTgJbw8ECzgQ8xSQLraAX3FnK1CJ2E=,tag:MAWesUY/x5VldjiTNjjPPQ==,type:str]
sops:
  age:
  - age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
  lastmodified: '2026-03-30T20:25:09Z'
  mac: ENC[AES256_GCM,data:hed8btiYI2S5qofY9+/aUaQtKfBqhwPC5QqT2sLf14fOatrkHdF/rs8mQXw6kG6V93HoAnPskXLGGtxpu+k3HOgWH/2rN/Do1nScsgu2o0upMHEu5M+vRw+St5FauYxXl8yaKWA1rjZLC2goqceF9czkp/evu2pbE9LyGPoqP/s=,iv:aVRv6GcGnYwBurkfKS+pn+yy3rWchG0ROqfgaB1tRns=,tag:kl8YAYvzDhFOHkHPyPzyAQ==,type:str]
  encrypted_regex: ^(passwd|user|password|stringData|secret\.yaml|auth_token|network_key|mqtt_.*)$
  version: 3.11.0
