apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-immich.sops.yaml
  - pvc.yaml
  - database.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - httproute.yaml
