apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1T
  storageClassName: nfs-spacex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-machine-learning-cache
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-flash

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-valkey
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-flash
