apiVersion: v1
kind: Secret
metadata:
    name: database-immich
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:+4OCCgvXOhBEV2keEIDfTrTfkqmXISNJ0A==,iv:OYEFGRLRGRLWja2hqGvcMbuZkxWNFBYXNOOihCtcI6Q=,tag:kisxjmu53xdL46fOfqJAZg==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:PSGcYA55,iv:dc4s2ci2IbK+hNVLsts1d7j8np8bc4XYcleXfxHeoic=,tag:ZBVXG2FBsImJviA46TBztQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:mPlJR6sq,iv:aLaSg5b6F62tZKkyPeIjXW7dYxYT/USVu24X+OInZBM=,tag:ozfrkXxXNyNmT8hL0gskSA==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:tJBjexjOVYNQV/NziLBrnv3jTtUv1O1ud+5oyyywK4TkD5F68Q==,iv:6QJRFP2G/UVxVYee/cZFVAMwRTX5mcZRf8TiIJ+HmHA=,tag:4o9ztgwVc/UohnvWo1GyZA==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMzgrV0VOYStSUzhRNGwr
            MDB2ajloQVBsd0R1RjdibmpNeXd0SUkvRjNVCmlRSG9kRVJHbzdLQWg3d0tMNDJX
            QUNHSE1SRm1IV09DMktXeHNrRWJvU0UKLS0tIGVGK29wdmRjbE9vanYwZEVjS05x
            Z2RtdUI0RnVWeXVKWGxyYXlKQk1LSHcKlAOzuJxZ+YqTzdVq4tYnaQtfbKGO8l6c
            xu9SUoLOJA2WSsl4P+v/dza7E43Wmjh9KQ9HzB98B+cwylM/h2MOdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T22:44:18Z"
    mac: ENC[AES256_GCM,data:wwe6A6pPDPmaV1V5Eq2tB43zzRBYBlyVjjO+2aGDfSq1cyUIqfnY2lal+Ip7cuVD8Eb4033LISCDNbr0nrawaeW0LwNPfIOUFHzksZt+HQvG+zbSrRymJ6lUOCng0cf+gnYxebnMRyICZQE9a2QGJ6OTNabx97DAKZefF61SYgE=,iv:gPfMoBTAmVYAr4tDLpj3uwH/CHGv6lh0mKPXVSXDjfU=,tag:+he2gSDnn2w7h2rhrd0uwA==,type:str]
    encrypted_regex: ^(passwd|user|password|stringData|secret\.yaml|auth_token|network_key|mqtt_.*)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-db-secret
    namespace: immich
stringData:
    username: ENC[AES256_GCM,data:XgTYFBn7,iv:3uYKMYXnemuouUm+ifnCewllUpvitNnC0YAn4mA6PP0=,tag:oiBtCazw99mOeeaB5EPPUA==,type:str]
    password: ENC[AES256_GCM,data:KIfsqGIrUzFeBPBE16eJtUn4D5H2ym6oWA==,iv:FjYnV1IiD9MoCmGA3OUm6mNEqshcur7+9Qp+/HExErA=,tag:GIUV+0M5DeVhUGtQ5wPI8g==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMzgrV0VOYStSUzhRNGwr
            MDB2ajloQVBsd0R1RjdibmpNeXd0SUkvRjNVCmlRSG9kRVJHbzdLQWg3d0tMNDJX
            QUNHSE1SRm1IV09DMktXeHNrRWJvU0UKLS0tIGVGK29wdmRjbE9vanYwZEVjS05x
            Z2RtdUI0RnVWeXVKWGxyYXlKQk1LSHcKlAOzuJxZ+YqTzdVq4tYnaQtfbKGO8l6c
            xu9SUoLOJA2WSsl4P+v/dza7E43Wmjh9KQ9HzB98B+cwylM/h2MOdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T22:44:18Z"
    mac: ENC[AES256_GCM,data:wwe6A6pPDPmaV1V5Eq2tB43zzRBYBlyVjjO+2aGDfSq1cyUIqfnY2lal+Ip7cuVD8Eb4033LISCDNbr0nrawaeW0LwNPfIOUFHzksZt+HQvG+zbSrRymJ6lUOCng0cf+gnYxebnMRyICZQE9a2QGJ6OTNabx97DAKZefF61SYgE=,iv:gPfMoBTAmVYAr4tDLpj3uwH/CHGv6lh0mKPXVSXDjfU=,tag:+he2gSDnn2w7h2rhrd0uwA==,type:str]
    encrypted_regex: ^(passwd|user|password|stringData|secret\.yaml|auth_token|network_key|mqtt_.*)$
    version: 3.11.0
