apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 41.2.0                         # ← aggiornato
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  upgrade:
    crds: Skip                                 # opzionale: valuta se gestire le CRD separatamente
    remediation:
      retries: 3
  install:
    crds: Skip
  values:

    # --- LOGGING (modificato) ---
    log:                                       # prima era logs.general
      level: WARN

    accessLog:                                 # prima era access
      enabled: true

    # --- CRD ---
    crds:
      enabled: false

    # --- DEPLOYMENT ---
    deployment:
      replicas: 2

    # --- PROVIDERS ---
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true

    # --- PORTS ---
    ports:
      web:
        port: 8000
        exposedPort: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
      websecure:
        port: 8443
        exposedPort: 443
        tls:
          enabled: true
        transport:
          respondingTimeouts:
            readTimeout: 600s
            idleTimeout: 600s
            writeTimeout: 600s
        middlewares:
          - traefik-traefik-errors@kubernetescrd

    # --- INGRESS ROUTE DASHBOARD ---
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.${DOMAIN}`)
        entryPoints: ["websecure"]
        middlewares:
          - name: authentik-forward-auth
          - name: traefik-errors

    # --- GATEWAY ---
    gateway:
      namespacePolicy: All

    # --- SERVICE ---
    service:
      annotations:
        metallb.io/ip-allocated-from-pool: external-pool
        metallb.io/allow-shared-ip: external-pool
        metallb.io/loadBalancerIPs: 192.168.178.10

    # --- RESOURCES ---
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
