apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tlsstore.yaml
  - gateway.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - middleware.yaml
  - catch-all.yaml

configMapGenerator:
  - name: traefik-error-pages
    namespace: traefik
    files:
      - error-pages/404.html
      - error-pages/503.html
      - error-pages/500.html
      - error-pages/index.html
