apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/prowlarr
      sourceRef:
        kind: GitRepository
        name: media-servarr
        namespace: flux-system
  targetNamespace: media
  values:
    podSecurityContext:
      fsGroup: 1000
    securityContext:
      runAsUser: 1000
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
