apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - pvc.yaml
  - secret-prowlarr.sops.yaml
  - httproute.yaml
metadata:
  name: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
