apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secrets
  namespace: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr-secrets
type: Opaque
stringData:
  # TODO: fill and encrypt with sops
  api_key: ""
sops:
  version: "3.11.0"
