apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-matter-server-data
  namespace: home-assistant-matter-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-spacex"
  resources:
    requests:
      storage: 2Gi
