apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - pvc.yaml
  - secret-transmission.sops.yaml
  - httproute.yaml
metadata:
  name: transmission
  labels:
    app.kubernetes.io/name: transmission
