apiVersion: v1
kind: Secret
metadata:
  name: transmission-secrets
  namespace: transmission
  labels:
    app.kubernetes.io/name: transmission-secrets
type: Opaque
stringData:
  # TODO: replace with real credentials and encrypt with sops
  webui_username: ""
  webui_password: ""
sops:
  version: "3.11.0"
