apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
  labels:
    app.kubernetes.io/name: zigbee2mqtt
spec:
  interval: 5m
  chart:
    spec:
      chart: zigbee2mqtt
      version: "2.8.0"
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: flux-system
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 2.10.1
    service:
      # -- annotations for the service created
      annotations:
        metallb.io/ip-allocated-from-pool: external-pool
        metallb.io/allow-shared-ip: external-pool
        metallb.io/loadBalancerIPs: 192.168.178.11
      # -- type of Service to be created
      type: LoadBalancer
      # -- port in which the service will be listening
      port: 8080
    statefulset:
      # -- annotations for the statefulset created
      annotations: {}
      # -- annotations for the pod template
      podAnnotations: {}
      storage:
        enabled: true
        size: 1Gi
        # -- the name for the storage class to be used in the persistent volume claim
        storageClassName: nfs-spacex
        existingVolume: ""
        ## Persistent Volume selectors
        ## https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
        matchLabels: {}
        matchExpressions: {}
        # -- annotations to add to the persistent volume claim
        annotations: {}
      secrets:
        # -- the name for the kubernets secret to mount as secret.yaml. This can be referenced in the config
        # by using advanced configurations https://www.zigbee2mqtt.io/guide/configuration/frontend.html#advanced-configuration
        name: "mqtt-auth"
      # -- name of pod priority class
      priorityClassName: ""
      # -- pod dns policy
      dnsPolicy: ClusterFirst
      # -- CPU/Memory configuration for the pods
      resources:
        requests:
          memory: 600Mi
          cpu: 200m
        limits:
          memory: 600Mi
          cpu: 200m
      # -- Overrides the entrypoint of the container
      command: {}
      # -- Node taint tolerations for the pods
      tolerations: {}
      # -- Select specific kube node, this will allow enforcing zigbee2mqtt running
      # only on the node with the USB adapter connected
      nodeSelector: {}
      # -- Node affinity for the pods
      affinity: {}
      # -- Lifecycle configuration for the container
      lifecycle: {}
      # -- Configure Pods Security Context
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
      # -- Configure Container Security Context
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      # -- Configures Container liveness probe
      livenessProbe:
        failureThreshold: 5
        httpGet:
          path: /
          port: web
        initialDelaySeconds: 60
        timeoutSeconds: 10
        periodSeconds: 30
      # -- Additional volumeMounts to the server main container
      volumeMounts: []
      #  - mountPath: /usr/local/bin/my-binary
      #    name: custom-tools
      #    subPath: my-binary
      # -- Additional volumes to the server pod
      volumes: []
      #  - name: custom-tools
      #    emptyDir: {}
    zigbee2mqtt:
      homeassistant:
        enabled: true
        discovery_topic: "homeassistant"
        status_topic: "hass/status"
        legacy_entity_attributes: true
        legacy_triggers: false
      # -- Optional: allow new devices to join.
      permit_join: false
      timezone: Europe/Rome
      external_converters: []
      mqtt:
        # -- Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
        server: "mqtt://mosquitto.mqtt.svc.cluster.local:1883"
        # -- Optional: MQTT base topic for Zigbee2MQTT MQTT messages (default: zigbee2mqtt)
        # base_topic: zigbee2mqtt
        # -- Optional: absolute path to SSL/TLS certificate of CA used to sign server and client certificates (default: nothing)
        # ca: '/etc/ssl/mqtt-ca.crt'
        # -- Optional: absolute paths to SSL/TLS key and certificate for client-authentication (default: nothing)
        # key: '/etc/ssl/mqtt-client.key'
        # cert: '/etc/ssl/mqtt-client.crt'
        # -- Optional: MQTT server authentication user (default: nothing)
        user: '!secret.yaml mqtt_user'
        # -- Optional: MQTT server authentication password (default: nothing)
        password: '!secret.yaml mqtt_password'
        # -- Optional: MQTT client ID (default: nothing)
        # client_id: 'MY_CLIENT_ID'
        # -- Optional: disable self-signed SSL certificates (default: true)
        # reject_unauthorized: true
        # -- Optional: Include device information to mqtt messages (default: false)
        # include_device_information: true
        # -- Optional: MQTT keepalive in seconds (default: 60)
        # keepalive: 60
        # -- Optional: MQTT protocol version (default: 4), set this to 5 if you
        # use the 'retention' device specific configuration
        # version: 4
        # -- Optional: Disable retain for all send messages. ONLY enable if you MQTT broker doesn't
        # support retained message (e.g. AWS IoT core, Azure IoT Hub, Google Cloud IoT core, IBM Watson IoT Platform).
        # Enabling will break the Home Assistant integration. (default: false)
        # force_disable_retain: false
      serial:
        # -- Required: location of the adapter (e.g. CC2531).
        # USB adapters - use format "port: /dev/ttyACM0"
        # To autodetect the USB port, set 'port: null'.
        # Ethernet adapters - use format "port: tcp://192.168.1.12:6638"
        adapter: "ember"
        port: "/dev/ttyUSB0"
        disable_led: false
        # baudrate: 115200
      ota:
        # -- Minimum time between OTA update checks
        update_check_interval: 1440
        # -- Disable automatic update checks
        disable_automatic_update_check: false
      frontend:
        # -- If the front end should be enabled, true by default. Pod health checks are based on this, so disabling
        # it will cause an error loop unless health checks are updated.
        enabled: true
        # -- Mandatory, default 8080
        # port: 8080
        # -- Optional, empty by default to listen on both IPv4 and IPv6. Opens a unix socket when given a path instead of an address (e.g. '/run/zigbee2mqtt/zigbee2mqtt.sock')
        # Don't set this if you use Docker or the Home Assistant add-on unless you're sure the chosen IP is available inside the container
        # host: ""
        # -- Optional, enables authentication, disabled by default, cleartext (no hashing required)
        # auth_token: null
        # -- Optional, url on which the frontend can be reached, currently only used for the Home Assistant device configuration page
        # url: null
        package: zigbee2mqtt-windfront
    ingress:
      # -- When enabled a new Ingress will be created
      enabled: false
      # -- The ingress class name for the ingress
      ingressClassName: contour
      # -- Additional labels for the ingres
      labels: {}
      # -- Ingress implementation specific (potentially) for most use cases Prefix should be ok
      pathType: Prefix
      # Additional annotations for the ingress. ExternalDNS, and CertManager are tipically integrated here
      annotations: {}
      # -- list of hosts that should be allowed for the zigbee2mqtt service
      hosts:
        - host: chart-example.local
          paths:
            - path: /
              pathType: ImplementationSpecific
            - path: /api
              pathType: ImplementationSpecific
      # -- configuration for tls service (ig any)
      tls:
        - secretName: some-tls-secret
          hosts:
            - yourdomain.com
