apiVersion: v1
kind: Secret
metadata:
    name: mqtt-auth
    namespace: zigbee2mqtt
type: Opaque
stringData:
    secret.yaml: ENC[AES256_GCM,data:XqN9yatom6FanS8DWD5C9eCxdpg2HOXDfhHpWDKA4Gpab7n1Yg58Bm2qiTBdvjAWsdCzk7MxNlo=,iv:KYvhtFQAg/YhmW+VABc4519K/yUb1fzxQcIUa8FuTkc=,tag:PjNL2OMAXyrv2xyBB7t4Zg==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVVBRR1Q1NGpLMno4UHJL
            Q3FJKzRrV1NVZ2pvcDJZbE90enczcWY5WUJzCnF5L09ybmpsdXJ4MEYyYXZ2c1lx
            TDBxdWxnZ0VzbzNmTHR6R0ovSnI2RVEKLS0tIFJxVHlBd2t5Yk1qQUdndU5tZVBj
            cENhaWI0RGk4RzhrZXlMODVmNU1USWcK8M4oWrPlp09Bd4IMN86oiEX7yQhQ8BTE
            Wtdu83SLqgCFt6ehOojJGVuGsDxKRg7TZLtyVBmfr7hBM0evUyYXbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T22:00:11Z"
    mac: ENC[AES256_GCM,data:6nlp9AHgq15OBYgWnc/O7qu+1/vJNGFUiLLjp+UgbJnnVkf5hfGFzTabylLijNq9aioQghI5Bq44jF9+W+QnNxMznN4KJwnaGAnSiuodE1tajjSjiN5wDCeA/OyXzPXQb3Ks9L4CsalHF2otoGoQ5U4FDr0M7TixQFBR212b6BQ=,iv:CMpLFzf3Vexl9f4ydx3xyGhHW6ef3m9VswmAchEf1Gc=,tag:8IBN6DjV3jmhQww80EvH/Q==,type:str]
    encrypted_regex: ^(passwd|user|password|stringData|secret\.yaml|auth_token|network_key|mqtt_.*)$
    version: 3.11.0
