
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mosquitto
  namespace: flux-system
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  interval: 1h
  url: https://bdclark.github.io/helm-charts