apiVersion: v1
kind: Secret
metadata:
  name: mqtt-auth
  namespace: mqtt
  labels:
    app.kubernetes.io/name: mqtt-auth
type: Opaque
data:
  passwd: ENC[AES256_GCM,data:QvL2s9Pt9Ik7B3B9jR9hBuA9PAG5/Z3gwrwkunX5/RVB9Iz0QOwmOckb9vcYKhfsJhHq5G4A97QSfNxQEhDWA2N2clL7FBmE2KbysG7ebUQyUXYi9H/1hShyIE2EwDRW5hPlLJ0pMIKFjVAqb21vPMxO7+UUVMOT20gvDMjLG0xFMm2avahOcegKNlhuICxuaWSq5ElD6+0T4tzNodhV0aoGM1Y=,iv:wEeADi9BQbEwHnsb9eqdvNwQtnvz7qdgMRQykWK67f8=,tag:Bj8+yIkhNKiltkivlF/PDg==,type:str]
sops:
  age:
  - age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
  lastmodified: '2025-12-01T14:54:00Z'
  mac: ENC[AES256_GCM,data:M/zq2ST+fca4DV+DUcx4ZMc2KCF2GhD8dV6i8XvS6tY4QhILgovhybs4iHQjd6pEx8GzXf/wN5VXOHXzUKVXCwwGZiQ3JvFOIZ5zp/peRjbLtTMVqr9LGXYa06JEX7xPTVrynUJyQ6IYD46o0Fmf+wSXbhIe4WfqU1ALuf9aNcA=,iv:fonWjO1hximfgEqX1z1QxdyumDffiJ1jQ3eQ/Mu+XNk=,tag:zmcHsFycC2qPIwCvXLhpCg==,type:str]
  encrypted_regex: ^(passwd)$
  version: 3.11.0
