apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - secret-cloudflare.sops.yaml
  - cluster-issuer.yaml
  - certificate-wildcard.yaml
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
  annotations: {}
