apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:BgQ1LSRkEBCUISgu7NNBsi+h4X8CK78kTjFDuPLYF7un4400xEdoew==,iv:J3UYlfyeV4uFoPm3uTMrbIAXF1j/cNbGNx5BEjCF9+8=,tag:e4EkAh+PcSuDU64voHYJKw==,type:str]
sops:
    age:
        - recipient: age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZHl2WWk1dFFUc1dNazRD
            UWo1b0kzT3AySHpmbVBEQ040VnFrSUtySFJrCnQ2bXZ1MHBRTEpnQzVmemp5S0ov
            Mm03c2FOL1NIcjk5T0dPRDVtQWhoOVUKLS0tIGtyRzJKcUJxMm0vYjZTbzRLd0FF
            YlU3REZid2VMU1h0bmhKcXBNVnFnb3MKWr4o8LGqXu+u3kVlBsimd9jLxQ0MckJx
            5rGWGZoLWgOgzY17Imb94hpgwP4AS/lwLprwEatnnT/zaeE/HYYC0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T16:22:59Z"
    mac: ENC[AES256_GCM,data:Qo9TFSOE83Y37Arj6gw42IGGbVuzZs2cdVJzkzvLlxSeF2ctSyCukOXGICOqfYMddg0j6TF8/ll5i6j95i4DE4kfIYsuFEgucV4Fq3eeLrWqk27RqBPgNGuenw25qXbdBK8Xzxm/80U34XdEKEuOEvcKEiVF/NsQ9ICgOu1+fr0=,iv:s9toQtW2A3nx6fLyHWHA7N9aG44sDMa+EpSGJ/6TWow=,tag:aw86pjU+5Yly92NMyTJU3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
