apiVersion: v1
kind: Service
metadata:
  name: aurral
  namespace: aurral
  labels:
    app.kubernetes.io/name: aurral
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: aurral
