apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - mosquitto
  - zigbee2mqtt
  - home-assistant
  - home-assistant-matter-server
  - immich
  - tado-api-proxy
  - gatus
  - prometheus
  - grafana
  - external-services
  - trek
  - social-media-reuploader
  - musicseerr
  - soulsync
  - aurral
  - profilarr
  - slskd
  - media-servarr
  - k8s-at-home
  - transmission
