apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: grafana
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-spacex
  resources:
    requests:
      storage: 1Gi
