apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana-admin
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:5JymN/o=,iv:Q0AGRGSL2Dem1sPPjHkgbcrkTHG3b/VUaEfdCONulXg=,tag:HEl+NTHvUqjcEQl+Qs45fw==,type:str]
  admin-password: ENC[AES256_GCM,data:7nRAue2QDqBGyMR8uTiMmdc+jxVMVdeesvo=,iv:7bYpuEGw5GcGQ83DAmwHpHwCJghq0yyYLJYtsIRK5HQ=,tag:4+Irx9dJlq8S1r54wnOKiQ==,type:str]
sops:
  age:
  - age1tsc9gq8u66ufrv526fsvahg88pd030t42xe4msc4cm2z84dtke2qpwjnwd
  lastmodified: '2026-02-10T12:04:15Z'
  mac: ENC[AES256_GCM,data:Yd6ieO8uEcrwU7dNMySS+mRTnzPgbOdkgWhvmQhWYQczTcwzzswU8tX+GHD5XFdRkBf7+aXcJMPUerkc2qqXeFBskgrmAp0fOvpmqBZ794YZZZmj10GW+1C9A4f8NCUiw6mWeUoGuZDOntCaYUX3QYRGF+mxTzSEedaWcSvDm28=,iv:00FHEBnv5v/XeeI+moQnEg6a9HOG8ZSqFvXokFGrrIU=,tag:RS+bz9QOtsxpSwgvkdeeGg==,type:str]
  encrypted_regex: ^(passwd|user|password|stringData|secret\.yaml|auth_token|network_key|mqtt_.*)$
  version: 3.11.0
