apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  namespace: prometheus
  labels:
    release: prometheus
    app.kubernetes.io/name: prometheus
spec:
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      interval: 30s
