apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: alexmorbo-slskd
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/alexmorbo/helm-charts/slskd
