apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-storage
  namespace: slskd
  labels:
    app.kubernetes.io/name: slskd-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-spacex
