apiVersion: v1
kind: Secret
metadata:
  name: slskd-secrets
  namespace: slskd
  labels:
    app.kubernetes.io/name: slskd-secrets
type: Opaque
stringData:
  # TODO: encrypt with sops
  token: ""
sops:
  version: "3.11.0"
